### PR TITLE
Dev 2.1.x

### PR DESCRIPTION
**Pull request by bigboi900**

### CODE REVIEW

**Comment by bigboi900** [comment]
Testing pull request

**Comment by mikesoule** [comment]
@bigboi900 Please let us know if you find it useful and have some suggestions. This package has room for improvement but we're using it on a couple projects and it works pretty well so far. The biggest challenge we've had with trying to make it a truly universal session drop-in is that PHP sessions are written at the beginning of the request whereas JWTs usually need to be generated at the end.

We're open to contributions that help make this package a more universal Phalcon session replacement while, of course, sticking tight to the JWT standard.

**Comment by bigboi900** [comment]
@mikesoule it would be awesome if we had a branch for the phalcon 2.1

**Comment by mikesoule** [comment]
@bigboi900 I just started working on a Phalcon 2.1 project so I should have an update for this in the next week.

**Pull request closed without merging**
